import Stylesheet from "reactjs-stylesheet";

const styles = Stylesheet.create({
	layout: {
    display: "flex",
    flexDirection: "row",
    width: '100%',
    height: "100%",
    minHeight: '90vh',
    justifyContent: 'center',
	},
  container1: {
    display: 'flex',
    flexDirection: 'column',
    width: '33%',
  },
  container2: {
    display: 'flex',
    flexDirection: 'column',
    width: '33%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemWrap1: {
    width: '100%',
    marginTop: 18,
  },
  itemWrap2: {
    width: '100%',
    marginBottom: 24,
    marginRight: 160,
  },
  itemWrap3: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    marginBottom: 24,
    alignItems: 'flex-end',
  },
  subTitleWrapView1: {
    display: 'flex',
    padding: 24,
  },
  // subTitleWrapView2: {
  //   display: 'flex',
  //   padding: 0,
  //   alignItems: 'flex-end',
  // },
  // subTitleWrapView3: {
  //   display: 'flex',
  //   padding: 24,
  //   alignItems: 'flex-end',
  //   backgroundColor: 'green'
  // },
  subTitleLineWrapView1: {
    display: 'flex',
    flexDirection: 'column', 
  },
  subTitleLineWrapLabel1: {
    display: 'flex',
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  subTitleLineWrapImage1: {
    width: 90,
    height: 4,
    resizeMode: 'contain',
  },
  subTitleLineWrapImage2: {
    width: 380,
    height: 13,
    marginTop: 12,
  },
  subTitleWrapView2: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    paddingLeft: 24,
    paddingRight: 80,
  },
  subTitleWrapView3: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    paddingLeft: 24,
    paddingRight: 40,
  },
  subWeatherCateogryItemView1: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: -10
  },
  subWeatherCateogryItemView2: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  subWeatherCateogryItemView3: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    paddingLeft: 24,
    paddingRight: 40,
    alignItems: 'end',
  },
  subWeatherCateogryItemView4: {
    display: 'flex',
    flexDirection: 'column',
    width: 470,
    paddingLeft: 24,
    paddingRight: 24,
    justifyContent: 'flex-end',
    marginTop: -8,
  },
  subWeatherCateogryItemSubView1: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 420,
  },
  subWeatherCateogryItemSubView2: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 420,
    marginTop: 16,
  },
  subWeatherCateogryItemSubView3: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    marginTop: -8,
  },
  subWeatherCateogryTableItemSubView1: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottom: '1px solid #347eed', 
    paddingTop: 8,
    paddingBottom: 8,
  },
  subWeatherCateogryTableItemSubView2: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between', 
    paddingTop: 8,
    paddingBottom: 8,
  },
  subWeatherCateogryItem1: {
    display: 'flex',
    flexDirection: 'row',
    width: 140,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  subWeatherCateogryItem2: {
    display: 'flex',
    flexDirection: 'row',
    width: 140,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: 80,
  },
  subWeatherCateogryItemWeatherIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  subWeatherCateogryTableItemSubViewTitle1: {
    display: 'flex',
    color: 'white',
    // widows: '100%',
    textAlign: 'left',
    // backgroundColor: 'yellow'
  },
  subWeatherCateogryTableItemSubViewTitle2: {
    display: 'flex',
    color: 'white',
    widows: '25%',
    textAlign: 'left',
    alignItems: 'center',
  },
  subWeatherCateogryTableItemSubViewTitle3: {
    display: 'flex',
    color: 'white',
    widows: '25%',
    alignItems: 'center',
  },
  blankSpinLogoLayout: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 100,
  },
  infoWrapper: {
    display: 'flex',
    position: 'absolute',
    top: 60,
    right: 20,
    width: 350,
    height: 600,
    flexDirection: 'column',
    padding: 20,
    // backgroundColor: 'red'
  },
  mapContainer: {
    margin: 18,
    display: 'flex',
    width: '100%',
    height: '100%',
    position: 'relative',
    border: '2px solid #347eed', 
  },
  smallPercentValueUpText: {
    display:'flex',
    color: 'red',
    textAlign: 'left',
    fontSize: 12,
  },
  smallPercentValueDownText: {
    display:'flex',
    color: '#02deff',
    textAlign: 'left',
    fontSize: 12,
  },
});
export default styles;
